### ISSUE TITLE
Migrate to PHP7

### ISSUE THREAD

**Issue by rebel-l** [fashionforhome/tico#5]
Make sure the application runs also with PHP7.

**Comment by rebel-l** [comment]
A quick test with PHP7.0.9 showed the following problem:
`Fatal error: Uncaught ReflectionException: Class log does not exist in /vagrant/vendor/laravel/framework/src/Illuminate/Container/Container.php:737 Stack trace: #0 /vagrant/vendor/laravel/framework/src/Illuminate/Container/Container.php(737): ReflectionClass->__construct('log') #1 /vagrant/vendor/laravel/framework/src/Illuminate/Container/Container.php(627): Illuminate\Container\Container->build('log', Array) #2 /vagrant/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(674): Illuminate\Container\Container->make('log', Array) #3 /vagrant/vendor/laravel/framework/src/Illuminate/Container/Container.php(838): Illuminate\Foundation\Application->make('log') #4 /vagrant/vendor/laravel/framework/src/Illuminate/Container/Container.php(801): Illuminate\Container\Container->resolveClass(Object(ReflectionParameter)) #5 /vagrant/vendor/laravel/framework/src/Illuminate/Container/Container.php(770): Illuminate\Container\Container->getDependencies(Array, Array) #6 /vagrant/vendor/laravel/framework/src/Illuminate/Contain in /vagrant/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 737`
